/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class CrossbeamArrayQueue {
  constructor(capacity: number)
  push(item: string): boolean
  pop(): string | null
  isEmpty(): boolean
  isFull(): boolean
  len(): number
  capacity(): number
}

export declare class CrossbeamAtomicCell {
  constructor(initialValue: number)
  load(): number
  store(value: number): void
  swap(value: number): number
  compareExchange(current: number, newValue: number): boolean
  fetchAdd(value: number): number
  fetchSub(value: number): number
}

export declare class CrossbeamChannel {
  constructor(bounded?: number | undefined | null)
  send(message: string): boolean
  receive(): string | null
  isEmpty(): boolean
  len(): number
}

export declare class CrossbeamSegQueue {
  constructor()
  push(item: string): void
  pop(): string | null
  isEmpty(): boolean
  len(): number
}

export declare class MultithreadingManager {
  constructor()
  initializeRayon(config?: RayonConfig | undefined | null): void
  initializeTokio(config?: TokioRuntimeConfig | undefined | null): void
  getRayonPool(): boolean
  getTokioRuntime(): boolean
  isRayonInitialized(): boolean
  isTokioInitialized(): boolean
  cleanup(): void
}

export declare class RayonThreadPool {
  constructor(config?: RayonConfig | undefined | null)
  currentNumThreads(): number
}

export declare class TokioBroadcastChannel {
  constructor(capacity: number)
  send(message: string): number
  receiverCount(): number
}

export declare class TokioMpscChannel {
  constructor()
}

export declare class TokioRuntime {
  constructor(config?: TokioRuntimeConfig | undefined | null)
}

export declare class TokioTimer {
  constructor()
  elapsedMs(): number
  reset(): void
}

export declare function benchmarkParallelOperations(dataSize: number, operation: string): Promise<unknown>

export interface BenchmarkResult {
  operation: string
  dataSize: number
  result: number
  durationMs: number
  throughput: number
}

export declare function createCrossbeamArrayQueue(capacity: number): CrossbeamArrayQueue

export declare function createCrossbeamAtomicCell(initialValue: number): CrossbeamAtomicCell

export declare function createCrossbeamChannel(bounded?: number | undefined | null): CrossbeamChannel

export declare function createCrossbeamSegQueue(): CrossbeamSegQueue

export declare function createRayonThreadPool(config?: RayonConfig | undefined | null): RayonThreadPool

export declare function createTokioBroadcastChannel(capacity: number): TokioBroadcastChannel

export declare function createTokioMpscChannel(): TokioMpscChannel

export declare function createTokioRuntime(config?: TokioRuntimeConfig | undefined | null): TokioRuntime

export declare function createTokioTimer(): TokioTimer

export declare function getMultithreadingInfo(): string

export declare function getPerformanceMetrics(): PerformanceMetrics

export declare function getRayonGlobalThreadCount(): number

export declare function getSystemInfo(): SystemInfo

export declare function getTokioRuntimeMetrics(): string

export declare function initializeMultithreading(): string

export declare function parallelChunkProcess(data: Array<number>, chunkSize: number, operation: string, pool?: RayonThreadPool | undefined | null): Promise<unknown>

export declare function parallelFilter(data: Array<number>, operation: string, threshold?: number | undefined | null, pool?: RayonThreadPool | undefined | null): Promise<unknown>

export declare function parallelMap(data: Array<number>, operation: string, pool?: RayonThreadPool | undefined | null): Promise<unknown>

export declare function parallelReduce(data: Array<number>, operation: string, initial?: number | undefined | null, pool?: RayonThreadPool | undefined | null): Promise<unknown>

export declare function parallelSort(data: Array<number>, descending?: boolean | undefined | null, pool?: RayonThreadPool | undefined | null): Promise<unknown>

export interface PerformanceMetrics {
  cpuCores: number
  rayonThreads: number
  memoryUsageMb: number
  uptimeMs: number
  activeTasks: number
}

export interface RayonConfig {
  numThreads?: number
  threadName?: string
  stackSize?: number
  panicHandler?: boolean
}

export declare function shutdownMultithreading(): string

export declare function stressTestConcurrency(numTasks: number, taskDurationMs: number, callback: ((err: Error | null, arg: StressTestResult) => any)): void

export interface StressTestResult {
  taskId: number
  durationMs: number
  threadId: string
  status: string
}

export interface SystemInfo {
  cpuCores: number
  rayonThreads: number
  tokioAvailable: boolean
  crossbeamAvailable: boolean
  version: string
}

export declare function tokioDelay(durationMs: number, message: string): Promise<unknown>

export declare function tokioParallelTasks(tasks: Array<string>, delayMs: number): Promise<unknown>

export interface TokioRuntimeConfig {
  workerThreads?: number
  maxBlockingThreads?: number
  threadName?: string
  threadStackSize?: number
  enableIo?: boolean
  enableTime?: boolean
}

export declare function tokioTimeout(durationMs: number, timeoutMs: number, operation: string): Promise<unknown>
