import { defineConfig } from 'https://deno.land/x/deno_test@0.1.0/mod.ts';

export default defineConfig({
  include: [
    'core/src/**/*.{test,spec}.{js,ts,jsx,tsx}',
    'remix/app/**/*.{test,spec}.{js,ts,jsx,tsx}',
    'next/src/**/*.{test,spec}.{js,ts,jsx,tsx}',
    'shared/src/**/*.{test,spec}.{js,ts,jsx,tsx}',
    'tests/unit/**/*.{test,spec}.{js,ts,jsx,tsx}',
  ],
  exclude: [
    'node_modules/**',
    'dist/**',
    '.next/**',
    '.remix/**',
    'tests/e2e/**',
    'shared/src/native/**',
  ],
  permissions: {
    read: true,
    write: true,
    net: true,
    env: true,
    run: true,
  },
  coverage: {
    include: [
      'core/src/**/*.{js,ts,jsx,tsx}',
      'remix/app/**/*.{js,ts,jsx,tsx}',
      'next/src/**/*.{js,ts,jsx,tsx}',
      'shared/src/**/*.{js,ts,jsx,tsx}',
    ],
    exclude: [
      'node_modules/**',
      'tests/**',
      '**/*.d.ts',
      '**/*.config.{js,ts}',
      '**/coverage/**',
      '**/dist/**',
      '**/.next/**',
      '**/.remix/**',
      'shared/src/native/**',
    ],
    reporter: ['text', 'json', 'html', 'lcov'],
    thresholds: {
      branches: 80,
      functions: 80,
      lines: 80,
      statements: 80,
    },
  },
  compilerOptions: {
    allowJs: true,
    allowSyntheticDefaultImports: true,
    allowUnreachableCode: false,
    allowUnusedLabels: false,
    alwaysStrict: true,
    assumeChangesOnlyAffectDirectDependencies: false,
    checkJs: false,
    declaration: true,
    declarationMap: true,
    emitDecoratorMetadata: true,
    exactOptionalPropertyTypes: true,
    experimentalDecorators: true,
    importsNotUsedAsValues: 'error',
    jsx: 'react-jsx',
    jsxImportSource: 'react',
    lib: ['dom', 'dom.iterable', 'es6'],
    module: 'esnext',
    moduleResolution: 'node',
    noFallthroughCasesInSwitch: true,
    noImplicitAny: true,
    noImplicitOverride: true,
    noImplicitReturns: true,
    noImplicitThis: true,
    noPropertyAccessFromIndexSignature: true,
    noUncheckedIndexedAccess: true,
    noUnusedLocals: true,
    noUnusedParameters: true,
    resolveJsonModule: true,
    skipLibCheck: true,
    strict: true,
    strictBindCallApply: true,
    strictFunctionTypes: true,
    strictNullChecks: true,
    strictPropertyInitialization: true,
    target: 'es2022',
    useDefineForClassFields: true,
  },
  importMap: './deno.json',
});
