pipeline {
    agent {
        kubernetes {
            yaml """
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: sota-marketing-stack
spec:
  containers:
  - name: deno
    image: denoland/deno:1.32.0
    command:
    - cat
    tty: true
  - name: node
    image: node:16
    command:
    - cat
    tty: true
"""
        }
    }
    
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Lint') {
            steps {
                container('deno') {
                    sh 'deno task lint'
                }
            }
        }
        
        stage('Test') {
            steps {
                container('deno') {
                    sh 'deno task test'
                }
            }
        }
        
        stage('Build') {
            steps {
                container('deno') {
                    sh 'deno task build'
                }
            }
        }
        
        stage('Deploy') {
            when {
                branch 'main'
            }
            steps {
                container('node') {
                    sh '''
                    npm install -g netlify-cli
                    netlify deploy --dir=dist --prod
                    '''
                }
            }
        }
    }
    
    post {
        always {
            archiveArtifacts artifacts: 'dist/**/*', allowEmptyArchive: true
        }
    }
}

/*
 * © 2025 Spectrum Web Co LLC. All rights reserved.
 * This code is the property of Spectrum Web Co LLC.
 * Licensed under MIT License.
 */
